### PR TITLE
Filesystem Experimental Header Not Implemented In C++17

### PR DESCRIPTION
**Pull request by r2dr0dn**
the filesystem library was not yet implemented in the ```std::filesystem``` namespace. It, along with any other <experimental/...> headers that are included in the ```olcPixelGameEngine.h``` For C++17, are in the ```std::experimental``` namespace.

### CODE REVIEW

**Comment by OneLoneCoder** [comment]
image

**Comment by DCubix** [comment]
You should probably update your compiler, especially if it's GCC 😅

**Comment by IGR2014** [comment]
I can confirm on my MSVC 2019 v16.4.4 <filesystem> header is only available when /std:c++latest compiler parameter specified. But not when /std:c++17

**Comment by DangermaN7** [comment]
The header requires modification to compile using Linux Mint 19.3. Filesystem is in the experimental subdirectory, but the header file does not allow for that if __linux__ is defined.

**Pull request closed without merging**
